### ISSUE TITLE
Multiple outfits are displayed at the same time

### ISSUE THREAD

**Issue by Rick22233** [xxk-i/NASA#3]
I had the kimono on and went to Chapter 11.1 and this happened...

The white dress and hair are peaking through, and the kimono sleeves are still attached.

Are there any fixes for this?

Thank you!

**Comment by xxk-i** [comment]
Hi, thanks for the report!

No fixes currently, unfortunately I personally will not be working on this project anytime soon. Leaving this issue open for anyone else to look at in the future.

**Comment by xxk-i** [comment]
Issue resolved by @mpchu
